#url: "https://geonovum.github.io"
repo_url: "https://github.com/Geonovum/IMGeo-objectenhandboek"
base_url: "/IMGeo-objectenhandboek-dev"
title: IMGeo objectenhandboek
lang: nl
description: Praktijkhandleiding voor toepassing van de BGT|IMGeo standaarden bij de objectafbakening

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  #- jekyll-remote-theme

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

theme: null
#remote_theme: clearpathrobotics/jekyll-rtd-theme

include:
  - _theme



layouts_dir: _theme/_layouts
includes_dir: _theme/_includes
sass:
  sass_dir: _theme/_sass

  
readme_index:
  with_frontmatter: true 
